dataset_dir: 'VOC/VOCdevkit'
tf_model_path: 'saved_models/tf'
compressed_model_path: 'saved_models/compressed_power_of_two/model_save/'
input_node: 'input_1:0'
output_node: 'predictions/concat:0'
img_height: 224
img_width: 224
batch_size: 4
epochs: 2
learning_rate: 0.0001
