dataset_dir: '/keras_ssd_mobilenet_v2/VOC/VOCdevkit'
tf_model_path: '/keras_ssd_mobilenet_v2/saved_models/tf/'
compressed_model_path: '/keras_ssd_mobilenet_v2/saved_models/compressed/'
input_node: 'input_1:0'
output_node: 'predictions/concat:0'
img_height: 300
img_width: 300
batch_size: 2
epochs: 1
learning_rate: 0.0003